name: Code changes comment

# **What it does**: When a PR is opened in docs-internal or docs containing code, it comments with instructions on how to deploy and preview the changes.
# **Why we have it**: To help Docs contributors understand how to preview their changes.
# **Who does it impact**: docs-internal andd docs maintainers and contributors

on:
  workflow_dispatch:
    inputs:
      PR_NUMBER:
        description: 'PR Number'
        type: string
        required: true
      BASE_SHA:
        description: 'Base SHA'
        type: string
        required: true
        default: 'main'
      HEAD_SHA:
        description: 'Head SHA (latest sha of the PR)'
        type: string
        required: true
  # Required in lieu of `pull_request` so that the content changes tables can be posts to PRs opened from a fork.
  pull_request_target:
    types:
      - opened
      - synchronize
    paths-ignore:
      - 'content/**'
      - 'data/reusables/**'

permissions:
  contents: read
  pull-requests: write

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  postOnCodeChanges:
    if: ${{ github.event.pull_request.user.login != 'docs-bot'}}
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number || inputs.PR_NUMBER }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
      REPO: 'github/docs'
    steps:
      - name: check out repo content
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Find code changes comment
        uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e
        id: findComment
        with:
          issue-number: ${{ github.event.pull_request.number || inputs.PR_NUMBER }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- CODE_CHANGES_COMMENT -->'

      # TODO: We'll update this comment at a later time with permament-ish links to deployment instructions.
      - name: Comment on code changes
        if: ${{ !steps.findComment.outputs.comment-id }}
        run: |
          if [[ "${{ env.REPO }}" == "github/docs" ]]; then
            COMMENT_BODY="## 🚀 Manual Deployment Required
            **This comment is 🤖 automatically generated.**

            It looks like his pull request contains code changes. To preview these changes, an internal Hubber will need to manually deploy the changes to one of our staging server.

            Thank you for your contribution!"
          else
            COMMENT_BODY="## 🚀 Manual Deployment Required
            **This comment is 🤖 automatically generated.**

            It looks like this pull request contains code changes. To preview these changes, you will need to deploy them manually.

            Thank you for your contribution!"
          fi

          gh pr comment ${{ env.PR_NUMBER }} --body "$COMMENT_BODY"
